services:
  bridge:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./conf:/usr/src/app/conf
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
    command: npm start
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
